Bookstore: initialize project with components
brenoxav/bookstore pull request #1
Opened 2021-08-30 22:05 UTC by brenoxav

## Bookstore: initialize project with components

- Create React app
- Add React Redux
- Structure application files using a "feature folder" approach
- Add base components
- Add React Router with two navigation links:
  - Books (default view)
  - Categories ("Under construction" text only)

2021-08-30 22:41 UTC, dasileker requested changes
### **Hi @brenoxav** 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-30 22:41 UTC, dasileker commented on src/components/Books.js
> +        <button type="button">Remove</button>
- [ ] The books should be added as prop types not like tags see the screenshot 👇

![hfhf](https://user-images.githubusercontent.com/61562626/131414908-d38e473b-0277-409a-8468-491f2aab8613.jpeg)

2021-08-30 23:00 UTC, brenoxav commented on src/components/Books.js
> +        <button type="button">Remove</button>
Hi @dasileker!
Thank you for your review.
I don't see that requirement anywhere in [the project instructions.](https://github.com/microverseinc/curriculum-react-redux/blob/main/bookstore/project_init_project_wth_comps.md)
I thought that would be necessary only in the next milestone.

2021-08-30 23:03 UTC, dasileker commented on src/components/Books.js
> +        <button type="button">Remove</button>
Hello @brenoxav 
I do see that is not mentioned in your requirement, but you are free to ask for another review. it will be better if you do add it.

2021-08-31 13:39 UTC, brenoxav commented on src/components/Books.js
> +        <button type="button">Remove</button>
Done.

2021-08-31 13:47 UTC, hemant-soni-vst-au4 approved these changes
Hi @brenoxav, 

## Your project is complete! 
There is nothing else to say other than... it's time to merge it :shipit: 

## Congratulations! 🎉 

Cheers and happy coding 😃

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. You can mention me (@hemant-soni-vst-au4) so I can see your comments and respond.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-31 13:47 UTC, merged